project_name: neveralone

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/neveralone
    binary: neveralone
    ldflags:
      - -s -w -X main.Version={{ .Version }} -X main.Commit={{.Commit}} -X main.Date={{ .CommitDate }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath

dockers:
    # Templates of the Docker image names.
    - image_templates:
      - "ghcr.io/neveralone:latest"
      - "ghcr.io/neveralone:{{ .Tag }}"

release:
  draft: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^ui:'