name: lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Restore Go modules cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('go.mod') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Verify dependencies
        run: |
          go mod verify
          go mod download

      - name: "Run go vet"
        run: "go vet ./..."

      - name: "Staticcheck"
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"